apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Xunhor/argocd'
    targetRevision: HEAD
    path: applications/grafana
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true       # remove recursos que saíram do Git
      selfHeal: true    # corrige drift automaticamente